using System;
using System.Linq;
using System.Collections.Generic;
using StoryGhost.Interfaces;

namespace StoryGhost.Models.Genres;

public class Drama : IGenre
{
    public string Id { get { return "drama"; } }
    public string Name { get { return "Drama"; } }
    public string Description { get { return "Drama is the tension created between extreme forces that oppose one another. It focuses on some aspect of humanity and tests it to the extreme, revealing intense emotions and challenging the relationships of the characters involved."; } }
    public List<string> Keywords
    {
        get
        {
            var listWithDupes = new List<string>{
                "conflict", "choice", "relatability", "opposites", "defeat", "triumph", "high stakes",

                // GPT-3 generated
                "betrayal", "secrets", "redemption", "survival", "courage",

            //"life",
            "love",
            //"lives",
            "home",
            "school",
            //"time",
            //"help",
            "death",
            "town",
            "mysterious",
            //"group",
            "war",
            //"meets",
            "relationship",
            "American",
            //"falls",
            //"living",
            //"forced",
            "work",
            "job",
            "discovers",
            //"decides",
            //"save",
            "police",
            "journey",
            //"left",
            "secret",
            "returns",
            "fight",
            "career",
            "beautiful",
            "local",
            "couple",
            "student",
            //"live",
            "prison",
            "future",
            "night",
            "house",
            "child",
            //"team",
            "city",
            "college",
            "dangerous",
            "children",
            "drug",
            "crime",
            "murder",
            //"makes",
            "friendship",
            "chance",
            //"turns",
            "battle",
            "escape",
            "mission",
            "struggles",
            "money",
            "violent",
            "personal",
            "marriage",
            "killer",
            "unexpected",
            "agent",
            "affair",
            "accident",
            "car",
            "revenge",
            "dead",
            //"gang",
            "estranged",
            "truth",

            // from newest KeyBERT notbook

            "family",
            "woman",
            "father",
            "New York",
            "American",
            "town",
            "daughter",
            "Los Angeles",
            "son",
            "prison",
            "British",
            "U.S.",
            "mother",
            "London",
            "wife",
            "life",
            "detective",
            "World War II",
            "falls",
            "journey",
            "Paris",
            "writer",
            "agent",
            "America",
            "Earth",
            "student",
            "gang",
            "crime",
            "school",
            "girl",
            "English",
            "journalist",
            "French",
            "FBI",
            "brother",
            "relationship",
            "marriage",
            "France",
            "Nazi",
            "husband",
            "England",
            "friends",
            "college",
            "house",
            "love",
            "police",
            "parents",
            "lawyer",
            "couple",
            "New York City",
            "death",
            "California",
            "escape",
            "beautiful",
            "teen",
            "sister",
            "romance",
            "children",
            "professor",
            "murder",
            "German",
            "drama",
            "teacher",
            "students",
            "affair",
            "apartment",
            "Chicago",
            "drug",
            "soldiers",
            "women",
            "teenage",
            "suburban",
            "mission",
            "teenager",
            "island",
            "battle",
            "romantic",
            "war",
            "village",
            "soldier",
            "faith",
            "kidnapped",
            "friendship",
            "childhood",
            "pilot",
            "wedding",
            "rescue",
            "returns",
            "United States",
            "dreams",
            "doctor",
            "wilderness",
            "Hollywood",
            //"stories",
            "accident",
            "coach",
            "sisters",
            "fall",
            "boy",
            "tragedy",
            "singer",
            "friend",
            "Texas",
            "heist",
            "fate",
            "travels",
            "brothers",
            "hometown",
            "author",
            "city",
            "CIA",
            "neighborhood",
            "dog",
            "fight",
            "law",
            "hotel",
            "supernatural",
            "assassin",
            "Rome",
            "Jewish",
            "save",
            "haunted",
            "cop",
            "Mexican",
            "adventure",
            "forced",
            "artist",
            "musician",
            "camp",
            "Italy",
            "estranged",
            "Japanese",
            "music",
            "dancer",
            "officer",
            "discovery",
            //"Christian",
            "existence",
            "conspiracy",
            "Manhattan",
            "plane",
            "actress",
            "Brooklyn",
            "book",
            "stay",
            "Iraq",
            "Mexico",
            "married",
            "terrorist",
            "star",
            "series",
            "violence",
            "killer",
            "wealthy",
            "farmer",
            "king",
            "heart",
            "dies",
            "boxer",
            "tragic",
            "chance",
            "crew",
            "band",
            "sergeant",
            "protect",
            "estate",
            "path",
            "widow",
            "Berlin",
            "Afghanistan",
            "criminal",
            //"mouse",
            "revenge",
            "dream",
            "president",
            "India",
            "fighter",
            "underworld",
            "evil",
            "hospital",
            "Spain",
            "named",
            "rural",
            "odds",
            "Russian",
            "plot",
            "Japan",
            "secret",
            "musical",
            "future",
            "boss",
            "live",
            "neighbor",
            "thief",
            "party",
            "relationships",
            //"rise",
            "daughters",
            "L.A.",
            "street",
            "career",
            "serial",
            "vengeance",
            "Irish",
            "powers",
            "child",
            "robbery",
            "actor",
            "San Francisco",
            "teenagers",
            "Germany",
            "photographer",
            "streets",
            "slavery",
            "survive",
            "birthday",
            "captain",
            "track",
            "passengers",
            "travel",
            "Britain",
            "meaning",
            "quest",
            //"sara",
            "fashion",
            "night",
            "astronaut",
            "consequences",
            "Italian",
            "executive",
            "prisoner",
            "lives",
            "colonel",
            "sinister",
            "officers",
            "African",
            "corruption",
            "Indian",
            "real",
            "summer",
            "trip",
            "gangster",
            "cousin",
            "crisis",
            "attorney",
            "siblings",
            //"meet",
            "chronicle",
            "haunting",
            };

            return listWithDupes.Distinct().ToList();
        }
    }

    public SequenceAdvices AdviceSequence
    {
        get
        {
            return new SequenceAdvices
            {
                Events = new AdviceSequence
                {
                    OpeningImage = "Tension is in the air.",
                    IncitingIncident = "An intensely stressful situation arises for the main character.",
                    Midpoint = "The main character overcomes some adversity for a brief reprieve from the stresses in their life."
                },
                Context = new AdviceSequence
                {

                }
            };
        }
    }

}