using System;
using System.Linq;
using System.Collections.Generic;
using StoryGhost.Interfaces;

namespace StoryGhost.Models.Genres;

public class Family : IGenre
{
    public string Id { get { return "family"; } }
    public string Name { get { return "Family"; } }
    public string Description { get { return "The Family genre contains children or relates to them in the context of home and family. Often covering topics of fear, authority, and reciprocal relationships."; } }
    public List<string> Keywords
    {
        get
        {
            var listWithDupes = new List<string>{

                "parents", "single parent", "sibling", "maturity",

                // GPT-3 generated
                "family dynamics", "long-lost relative", "reconciliation", "generational differences", "only child", "large family", "family secrets", "estrangement", "adoption", "multi-cultural family",

                //"life",
                //"save",
                "home",
                //"help",
                "Christmas",
                "evil",
                "adventure",
                "school",
                //"time",
                "love",
                "town",
                "secret",
                "team",
                "dog",
                "discovers",
                "meets",
                "discover",
                //"gang",
                "magical",
                "journey",
                "kids",
                "learn",
                "children",
                "Santa",
                "magic",
                //"live",
                "accidentally",
                "trip",
                //"decides",
                "quest",
                //"lives",
                //"mysterious",
                //"human",
                "city",
                "dreams",
                //"real",
                "lost",
                "plan",
                "search",
                "City",
                "mission",
                "house",
                //"return",
                "land",
                "powers",
                //"forces",
                "rescue",

                // from newest KeyBERT notbook

                "adventure",
                "family",
                "father",
                "dog",
                "save",
                "gang",
                "journey",
                "town",
                "parents",
                "Earth",
                "school",
                "princess",
                "children",
                "island",
                "monsters",
                "Santa",
                "dragon",
                "adventures",
                "daughter",
                "alien",
                "fairy",
                "evil",
                "holiday",
                "house",
                "kingdom",
                "quest",
                "powers",
                "animals",
                "mouse",
                "bear",
                "kids",
                "mother",
                "boy",
                "teenager",
                "girl",
                "orphan",
                "village",
                "robot",
                "monster",
                "friend",
                "friends",
                "dreams",
                "New York City",
                "cat",
                "puppy",
                "mansion",
                "fairies",
                "forest",
                "London",
                "canine",
                //"Scooby-Doo",
                "dinosaurs",
                "brothers",
                "sisters",
                "New York",
                "prince",
                "restore",
                "wizard",
                "book",
                "musical",
                "mermaid",
                "camp",
                //"asterix",
                "Paris",
                "summer",
                "castle",
                "jungle",
                "planet",
                "discover",
                "birthday",
                "meaning",
                "falls",
                "American",
                "space",
                "teen",
                "siblings",
                "sister",
                "vacation",
                "villains",
                "Gotham City",
                //"stories",
                "rescue",
                "hotel",
                "circus",
                "ghouls",
                "dogs",
                "dad",
                "North Pole",
                "uncle",
                "superheroes",
                "ready",
                "park",
                "christmas",
                "son",
                "animal",
                "normal",
                "aliens",
                "series",
                "battle",
                "city",
                "dragons",
                "Hollywood",
                "real",
                "ghost",
                "inventor",
                "wedding",
                "teens",
                "witches",
                "stolen",
                "supernatural",
                "ship",
                "toys",
                "captain",
                "royal",
                "America",
                "British",
                "mission",
                "nanny",
                "ranch",
                "rabbit",
                "elf",
                "life",
                "reunite",
                "teenage",
                "cousin",
                "warrior",
                "orphaned",
                "beautiful",
                "spy",
                "secret",
                // "Batman",
                // "Disney",
                "race",
                "pup",
                "pranks",
                "differences",
                "teach",
                "hatches",
                "escape",
                "witch",
                "California",
                "travels",
                //"Diego",
                "sidekick",
                "toy",
                "travel",
                "penguin",
                "lion",
                "penguins",
                "risk",
                "cast",
                "wolf",
                "fashion",
                "discovers",
                "plot",
                "brother",
                "grandfather",
                "ant",
                "moon",
                "Africa",
                "scientist",
                "inherits",
                "grandmother",
                "agent",
                "villain",
                "flying",
                "crew",
                "child",
                "deal",
                "mice",
                "beach",
                "farm",
                "live",
                "superpowers",
                "girls",
                "bring",
                "fortune",
                "nefarious",
                "Romans",
                "head",
                "embark",
                "music",
                "dance",
                //"including",
                "enchanted",
                "universe",
                "stranded",
                "werewolf",
                "orphanage",
                "forces",
                "Piglet",
                "friendship",
                "elephant",
                "wife",
                "boys",
                "monkey",
                "adorable",
                "professor",
                "garden",
                "trip",
                "vampire",
                "mom",
                "throne",
                //"Justice League",
                "cub",
                "owl",
                "team",
                //"Scooby",
                "ladybug",
                "childhood",
                "puppies",
                "gift",
                "ninjas",
                "Japan",
                "baseball",
                "recruited",
                "reindeer",
                "ghosts",
                "comic",
                "stepmother",
                "neighborhood",
                "existence",
                //"epic",
                "stage",
                "sara",
                "heart",
                "nephew",
                "intergalactic",
                "bird",
                "disappearance",
                "military",
                "mountain",
                "soccer",
                "hoping",
                "secrets",
                "steal",
                "wolves",
                "trio",
                "college",
                "sea",
                "portal",
                "Australia",
                "superhero",
                "supervillain",
                "romance",
            };
        
            return listWithDupes.Distinct().ToList();
        }
    }

    public SequenceAdvices AdviceSequence
    {
        get
        {
            return new SequenceAdvices
            {
                Events = new AdviceSequence
                {
                    // TODO
                },
                Context = new AdviceSequence
                {
                    OpeningImage = "The setting is lighthearted in tone.",
                }
            };
        }
    }

}