using System;
using System.Linq;
using System.Collections.Generic;
using StoryGhost.Interfaces;

namespace StoryGhost.Models.Genres;

public class Fantasy : IGenre
{
    public string Id { get { return "fantasy"; } }
    public string Name { get { return "Fantasy"; } }
    public string Description { get { return "Fantasy typically involves magical elements, is set in a vaguely medieval universe, and is inspired by fantastical folklore myths."; } }
    public List<string> Keywords
    {
        get
        {
            var listWithDupes = new List<string>{
                "magic", "wildness", "politics", "creatures", "legends", "supernatural",

                // GPT-3 generated
                "dragons", "wizards", "floating islands", "castle", "forest", "imprisonment", "riddles", "fairies", "hobbits", "werewolves", "vampires", "zombies", "angels", "demons", "ghosts", "witches", "warlocks", "elves", "trolls", "ogres", "goblins", "dwarves", "dungeon", "enchantment", "throne",

                "evil",
                //"life",
                //"save",
                "mysterious",
                //"time",
                //"help",
                "love",
                "magical",
                "home",
                "discovers",
                "ancient",
                "battle",
                "power",
                "King",
                "discover",
                "town",
                "Earth",
                "secret",
                "school",
                //"forces",
                "powers",
                "quest",
                "adventure",
                "journey",
                "powerful",
                "night",
                "land",
                //"living",
                "war",
                "children",
                //"falls",
                "protect",
                "human",
                "beautiful",
                "dark",
                //"forced",
                //"group",
                "monsters",
                "monster",
                "fight",
                //"return",
                "city",
                //"real",
                //"meets",
                "death",
                "dreams",
                //"live",
                //"lives",
                "search",
                "dragon",
                //"year",
                "kingdom",
                "princess",
                //"chance",
                //"team",
                "child",
                "vampire",
                "warrior",
                "fairy",
                //"epic",
                //"things",
                "accidentally",
                "strange",
                "escape",
                "island",
                "lost",
                "Queen",
                //"gang",
                "hope",
                "change",
                //"place"

                // from newest KeyBERT notbook

                "Earth",
                "town",
                "supernatural",
                "evil",
                "adventure",
                "vampire",
                "father",
                "dragon",
                "powers",
                "quest",
                "princess",
                "island",
                "monsters",
                "woman",
                "battle",
                "journey",
                "save",
                "children",
                "monster",
                "vampires",
                "family",
                "gang",
                "London",
                "wizard",
                "girl",
                "daughter",
                "discover",
                "kingdom",
                "hunter",
                "ancient",
                "ghosts",
                "boy",
                "prince",
                "alien",
                "fairy",
                "village",
                "warrior",
                "falls",
                "restore",
                "fairies",
                "adventures",
                "school",
                "king",
                "forces",
                "house",
                "witches",
                "dreams",
                "ghost",
                "wife",
                "American",
                "portal",
                "book",
                "fate",
                "castle",
                "England",
                "teenager",
                "birthday",
                "mother",
                "British",
                "magical",
                "mermaid",
                "dragons",
                "mansion",
                "sorcerer",
                "New York City",
                "escape",
                "faith",
                "Santa",
                "returns",
                "stories",
                "beautiful",
                "woods",
                "witch",
                "detective",
                "travels",
                "discovers",
                "werewolf",
                "existence",
                "deal",
                "city",
                "travel",
                "siblings",
                "dies",
                "elf",
                "reunite",
                "mission",
                "students",
                "wakes",
                "student",
                "immortal",
                "cat",
                "peter",
                "superheroes",
                "Paris",
                "parents",
                "holiday",
                "devil",
                "orphan",
                "forest",
                "teen",
                "superhero",
                "cast",
                "wolf",
                "magic",
                "captain",
                "future",
                "souls",
                "nanny",
                "destiny",
                "protect",
                "demon",
                "teenage",
                "secrets",
                "underworld",
                "vigilante",
                "World War II",
                "Japan",
                "sister",
                "spirits",
                "Neverland",
                "real",
                "childhood",
                "estate",
                "villains",
                "creatures",
                "force",
                "bear",
                "heroes",
                "throne",
                "North Pole",
                "love",
                "hotel",
                "wedding",
                "agent",
                "villain",
                "uncle",
                "fight",
                "Egypt",
                "planet",
                "businessman",
                "obsessed",
                "professor",
                "universe",
                "power",
                "dwarves",
                "risk",
                "musical",
                "suburban",
                "night",
                "war",
                "Disney",
                "grandmother",
                "apocalypse",
                "characters",
                "rabbit",
                "child",
                "kids",
                "America",
                "dark",
                "undead",
                "ghouls",
                "fantastical",
                "farmer",
                "friends",
                "moon",
                "track",
                "time",
                "friend",
                "enchanted",
                "beast",
                "stay",
                "rescue",
                "trapped",
                "orphaned",
                "plague",
                "secret",
                "mouse",
                "charming",
                "stepmother",
                "royal",
                "generations",
                "demons",
                "realm",
                "daniel",
                "death",
                "legacy",
                "murder",
                "underground",
                "animals",
                "embark",
                "hunt",
                "toy",
                "Manhattan",
                "haunted",
                "wizards",
                "threat",
                "nightmare",
                "bodies",
                "French",
                "intergalactic",
                "search",
                "tiny",
                "bring",
                "mortal",
                "ultimate",
                "voldemort",
                "strength",
                "ship",
                "tales",
                "comedy",
                "genetic",
                "relic",
                "nemesis",
                "humanity",
                "cousin",
                "werewolves",
                "party",
                "6th",
                "Mexico",
                "samurai",
                "snowy",
                "elves",
                "awakened",
                "songwriter",
                "singer",
                "dog",
                "New York",
                "sara",
                "life",
                "space",
                "scientist",
                "morticia",
                "add",
                "swashbuckling",
                "chance",
                "whimsical",
                "aliens",
                "mystery",
                "trio",
                "chipmunks",
                "accidentally",
                "darkness",
                "tragic",
                "anna",
                "brother",
            };
        
            return listWithDupes.Distinct().ToList();
        }
    }

    public SequenceAdvices AdviceSequence
    {
        get
        {
            return new SequenceAdvices
            {
                Events = new AdviceSequence
                {
                    OpeningImage = "Briefly show a physical or symbolic element that demonstrates this is a fantasy setting.",
                    Setup = "Show the fantasy setting in action, and how it permeates the everyday lives of the characters.",
                    FunAndGames = "Show the wildest and most extreme aspects of the fantasy setting, and how the characters treat it as mundane, having grown used to it."
                },
                Context = new AdviceSequence
                {

                }
            };
        }
    }

}