using System;
using System.Linq;
using System.Collections.Generic;
using StoryGhost.Interfaces;

namespace StoryGhost.Models.Genres;

public class Romance : IGenre
{
    public string Id { get { return "romance"; } }
    public string Name { get { return "Romance"; } }
    public string Description { get { return "Romance focuses on the relationship and courtship between two people."; } }
    public List<string> Keywords
    {
        get
        {
            var listWithDupes = new List<string>{
                "longing", "sacrifice", "marriage", "obsession", "infidelity",

                "unlikely relationship", "troubled marriage", "passionate embrace", "shy crush", "unrequited love", "secret love affair", "love at first sight", "disapproving family", "friend-zone", "love triangle", "secret workplace romance", "long-distance dating", "arranged marriage",

                "love",
                "life",
                //"falls",
                "relationship",
                "school",
                "meets",
                "lives",
                "romance",
                "time",
                "home",
                //"help",
                "beautiful",
                "town",
                //"discovers",
                "couple",
                "Christmas",
                "dreams",
                "mysterious",
                "romantic",
                //"decides",
                "work",
                //"living",
                "wedding",
                //"fall",
                "meet",
                "secret",
                "job",
                "affair",
                //"chance",
                "student",
                "married",
                "girlfriend",
                //"death",
                "boyfriend",
                "college",
                "night",
                "career",
                "heart",
                "keep",
                //"live",
                //"left",
                //"year",
                //"future",
                "house",
                "good",
                "discover",
                "single",
                "summer",
                "friendship",
                //"show",
                //"unexpected",
                "music",
                "different",
                //"like",
                "lover",
                "guy",
                "handsome",
                "local",
                "business",
                //"change",

                // from newest KeyBERT notbook

                "woman",
                "romance",
                "New York",
                "falls",
                "wedding",
                "family",
                "town",
                "father",
                "relationship",
                "love",
                "marriage",
                "American",
                "life",
                "daughter",
                "romantic",
                "British",
                "affair",
                "beautiful",
                "wife",
                "writer",
                "couple",
                "Hollywood",
                "married",
                "London",
                "Los Angeles",
                "fall",
                "women",
                "France",
                "friends",
                "school",
                "student",
                "college",
                "relationships",
                "princess",
                "French",
                "teenage",
                "New York City",
                "parents",
                "dating",
                "dreams",
                "journey",
                "English",
                "Paris",
                "party",
                "sister",
                "prince",
                "singer",
                "England",
                "island",
                "marry",
                "engaged",
                "author",
                "girl",
                "meet",
                "teen",
                "couples",
                "mother",
                "girlfriend",
                "San Francisco",
                "journalist",
                "heart",
                "professor",
                "artist",
                "musician",
                "waitress",
                "Manhattan",
                "teenager",
                "children",
                "Earth",
                "America",
                "royal",
                "cousin",
                "Italy",
                "dream",
                "hometown",
                "hotel",
                "dance",
                "tragedy",
                "husband",
                "series",
                "discover",
                "death",
                "stay",
                "travels",
                "fashion",
                "photographer",
                "European",
                "crush",
                "World War II",
                "drama",
                "bachelor",
                "comedy",
                "adventure",
                "bond",
                "divorced",
                "divorce",
                "Chicago",
                "book",
                "revenge",
                "vampire",
                "apartment",
                "friend",
                "lawyer",
                "poet",
                "chance",
                "faith",
                "marries",
                "obsessed",
                "business",
                "agent",
                "sisters",
                "age",
                "widow",
                "stepmother",
                "son",
                "dies",
                "holiday",
                "night",
                "United States",
                "spirit",
                "detective",
                "brother",
                "upside",
                "music",
                "fate",
                "adventures",
                "friendship",
                "executive",
                "summer",
                "assistant",
                "meets",
                "teacher",
                "meaning",
                "house",
                "band",
                "Spain",
                "dancer",
                "Rome",
                "heiress",
                "novelist",
                "illness",
                "secret",
                "wealthy",
                "kingdom",
                "songwriter",
                "boyfriend",
                "live",
                "Christian",
                "estranged",
                "prison",
                "reunite",
                "beach",
                "aristocrat",
                "girls",
                "senior",
                "cast",
                "stories",
                "actress",
                "boy",
                "tropical",
                "childhood",
                "advertising",
                "millionaire",
                "village",
                "Berlin",
                "cheerleader",
                "fiance",
                "anniversary",
                "classmate",
                "returns",
                "magazine",
                "rich",
                "spend",
                "battle",
                "estate",
                "throne",
                "German",
                "crisis",
                "courtship",
                "aunt",
                "save",
                "widower",
            };
        
            return listWithDupes.Distinct().ToList();
        }
    }

    public SequenceAdvices AdviceSequence
    {
        get
        {
            return new SequenceAdvices
            {
                Events = new AdviceSequence
                {
                    OpeningImage = "Breifly depict something symbolic of relationships and love.",
                    Setup = "Establish the complicated emotional (possibly romantic?) connections between the main characters.",
                    Debate = "Things get complicated as the emotional connections between characters shift.",
                    Midpoint = "The main character achieves what they think is the romantic connection they deeply desired, but it's fleeting.",
                    AllHopeIsLost = "The main character's romantic prospects are over.",
                    DarkNightOfTheSoul = "The main character accepts responsibility for the ruined relationship.",
                    BreakIntoThree = "The main character springs into action to attempt to make things right in their relationship.",
                    Cooldown = "Show how the main character's relationship is strong and healthy."
                },
                Context = new AdviceSequence
                {

                }
            };
        }
    }

}