using System;
using System.Linq;
using System.Collections.Generic;
using StoryGhost.Interfaces;
using StoryGhost.Enums;

namespace StoryGhost.Models.Genres;

public class Scifi : IGenre
{
    public string Id { get { return GenresEnum.ScienceFiction; } }
    public string Name { get { return "Science Fiction"; } }
    public string Description { get { return "Science Fiction is packed full of futuristic ideas, extrapolating from what's possible today into advanced science and technology. It examines the consequences of these innovations, and seeks to inspire a sense of forward-thinking wonder."; } }
    public List<string> Keywords
    {
        get
        {
            var listWithDupes = new List<string>{
                "technology", "future", "space", "aliens", "innovation", "time travel", "space travel", "scientific advances", "secret lab", "secret chemical", "serum", "weapon", "laser", "light speed", "rocket", "nebula", "telescope", "radio waves", "stellar transmission", "mega-structure", "hologram", "galaxy", "galactic map", "black hole", "gravity well", "energy pulse", "deep sea lab", "alien ruins", "asteroid field", "asteroid", "artificial intelligence", "teleport", "teleporter", "warp drive", "pulsar", "ancient alien civilization",

                // GPT-3 generated
                "AI", "premonitions", "parallel universe", "mind control", "clones", "alien invation", "robots", "cyborgs", "nanotechnology", "genetic engineering", "cybernetics", "virtual reality", "biotechnology", "machine learning", "genetic modification",

                "Earth",
                "planet",
                "alien",
                "life",
                "time",
                //"save",
                "mysterious",
                //"team",
                "mission",
                //"group",
                "human",
                "crew",
                //"help",
                "discover",
                "battle",
                "fight",
                "secret",
                //"evil",
                "home",
                "discovers",
                "war",
                "dangerous",
                "city",
                "Dr.",
                "government",
                "humans",
                "scientist",
                "humanity",
                "power",
                "powers",
                "force",
                "universe",
                "forces",
                //"lives",
                "deadly",
                "powerful",
                "escape",
                "survivors",
                //"year",
                "City",
                "virus",
                "ship",
                "sent",
                "survive",
                "creatures",
                "ancient",
                "attack",
                "love",
                //"town",
                "destroy",
                "robot",
                "strange",
                "threat",
                "protect",
                //"living",
                "mankind",
                "hope",
                //"series",
                "military",
                "control",
                "rescue",
                "search",
                "death",
                "game",
                "travel",
                //"plans"

                // from newest KeyBERT notbook

                "Earth",
                "alien",
                "planet",
                "crew",
                "aliens",
                "mission",
                "virus",
                "future",
                "space",
                "robot",
                "save",
                "woman",
                "father",
                "powers",
                "American",
                "survivors",
                "Los Angeles",
                "evil",
                "town",
                "soldier",
                "battle",
                "Mars",
                "scientist",
                "family",
                "astronaut",
                "agent",
                "heroes",
                "universe",
                "intergalactic",
                "apocalyptic",
                "cyborg",
                "island",
                "extraterrestrial",
                "discover",
                "population",
                "mankind",
                "rescue",
                "dinosaurs",
                "invasion",
                "protect",
                "escape",
                "cop",
                "prison",
                "discovery",
                "professor",
                "sharks",
                "zombies",
                "war",
                "shark",
                "humanity",
                "crime",
                "time",
                "New York City",
                "students",
                "force",
                "galaxy",
                "pilot",
                "teens",
                "humans",
                "spacecraft",
                "nuclear",
                "astronauts",
                "return",
                "New York",
                "band",
                "threat",
                "Gotham City",
                "apes",
                "supernatural",
                "DNA",
                "monster",
                "fate",
                "city",
                "robots",
                //"Autobots",
                "journey",
                "scientists",
                "moon",
                "creatures",
                "forced",
                "military",
                "machine",
                "wake",
                "America",
                "expedition",
                "underground",
                "futuristic",
                "friends",
                "restore",
                "cure",
                "meteor",
                "secret",
                "superheroes",
                "adventure",
                "mutant",
                "terrorist",
                "epidemic",
                "police",
                "superpowers",
                "plague",
                "dreams",
                "children",
                "species",
                "shuttle",
                //"Justice League",
                "travel",
                "wakes",
                "path",
                "ancient",
                "inhabitants",
                "send",
                "technology",
                "power",
                "fight",
                "soldiers",
                "uncharted",
                "memory",
                //"Man of Steel",
                "giant",
                "wife",
                "explorers",
                "villains",
                "stories",
                "parents",
                "romance",
                "zombie",
                "interstellar",
                "series",
                "school",
                "vampire",
                "death",
                "program",
                "World War II",
                "dimension",
                "Japan",
                "monsters",
                "ship",
                "experiment",
                "existence",
                "nemesis",
                "superhero",
                "resistance",
                //"Decepticons",
                "chance",
                "extinction",
                "U.S.",
                "accident",
                "submarine",
                "Mexico",
                "NASA",
                "life",
                "London",
                "disease",
                "hunt",
                "spaceship",
                "plan",
                "secrets",
                "conspiracy",
                "genetic",
                "teen",
                //"avengers",
                "consequences",
                "daughter",
                "United States",
                "teenager",
                "vengeance",
                "mercenaries",
                "enemy",
                "warrior",
                "race",
                "detective",
                "experiments",
                "destiny",
                "forces",
                "dystopian",
                "officer",
                "crash",
                "child",
                "desert",
                "CIA",
                "hacker",
                "doctor",
                "cosmic",
                "control",
                "house",
                "California",
                "memories",
                "virtual",
                "wasteland",
                "government",
                "criminals",
                "heroic",
                "girl",
                "invaders",
                "crocodile",
                "normal",
                "FBI",
                "inventor",
            };
        
            return listWithDupes.Distinct().ToList();
        }
    }

    public SequenceAdvices AdviceSequence
    {
        get
        {
            return new SequenceAdvices
            {
                Events = new AdviceSequence
                {
                    OpeningImage = "Briefly show a physical or symbolic element that demonstrates this is a futuristic scifi setting.",
                    Setup = "Show the scifi setting in action, and how it permeates the everyday lives of the characters.",
                    FunAndGames = "Show the most high-tech aspects of the fantasy setting, and how the characters treat it as mundane, having grown used to it."
                },
                Context = new AdviceSequence
                {

                }
            };
        }
    }

}