using System;
using System.Linq;
using System.Collections.Generic;
using StoryGhost.Interfaces;
using StoryGhost.Enums;

namespace StoryGhost.Models.Genres;

public class Sports : IGenre
{
    public string Id { get { return GenresEnum.Sports; } }
    public string Name { get { return "Sports"; } }
    public string Description { get { return "The Sports genre focuses on a game that dominates the Hero's life. The game is a backdrop for the Hero's struggles to overcome adversity."; } }
    public List<string> Keywords
    {
        get
        {
            var listWithDupes = new List<string>{
                "game", "losing", "winning", "overcome", "skill", "fan", "persistence",

                // GPT-3 generated
                "last in the league", "lack of equipment", "fanatic fans", "sports as a distraction from life", "pressure to perform", "coaching misfits", "cheating to win", "underhanded tactics", "sibling rivalry", "coming from behind", "team bonding", "friends and family of pro athletes", "benchwarmer", "lucky charms", "Cinerella story", "redemption", "sportsmanship",

                "team",
                "school",
                "coach",
                "player",
                //"life",
                "college",
                "match",
                "love",
                "home",
                //"save",
                "help",
                "play",
                "championship",
                "star",
                //"join",
                "pro",
                "dreams",
                "playing",
                "skills",
                "champion",

                // from newest KeyBERT notbook

                "coach",
                "baseball",
                "football",
                "boxing",
                "soccer",
                "school",
                "basketball",
                "golf",
                "hockey",
                "tennis",
                "daughter",
                "karate",
                "World War II",
                "rugby",
                "surfing",
                "family",
                "American",
                "athlete",
                "Texas",
                "journey",
                "fighter",
                "gang",
                "skating",
                "scholarship",
                "return",
                "odds",
                "championship",
                "Los Angeles",
                "friendship",
                "father",
                "swimming",
                "nation",
                "haunted",
                "college",
                "Japan",
                "Love",
                "plane",
                "Hawaii",
                "rival",
                "transform",
                "serial",
                "skateboarding",
                "comedy",
                "ice",
                "New York",
                "NBA",
                "crimes",
                "Philadelphia",
                "caddy",
                "falls",
                "Chicago",
                "parents",
                "poor",
                "prison",
                "camp",
                "boy",
                "heart",
                "fight",
                "club",
                "brother",
                "teenagers",
                "reunite",
                "golfer",
                "USA",
                "U.S.",
                "unscrupulous",
                "coming",
                "agent",
                "pool",
                "team",
                "draft",
                "France",
                "Russian",
                "volleyball",
                "heavyweight",
                "Jewish",
                "teenager",
                "kids",
                "mysterious",
                "film",
                "barrier",
                "Major League Baseball",
                "Brooklyn Dodgers",
                "Dodgers",
                "orphans",
                "Great Depression",
                "scrawny",
                "bohemian",
                "undercover",
                "freshmen",
                "adolescents",
                "brothers",
                "grandfather",
                "revenge",
                "hear",
                "returned",
                "funded",
                "springs",
                "Midwest",
                "America",
                "sisters",
                "bully",
                "diagnosed",
                "courage",
                "meager",
                "mountains",
                "Andes",
                "survive",
                "Uruguayan",
                "supernatural",
                "cheerleader",
                "coaster",
                "tragedy",
                //"Blackfoot High",
                //"The Mystery Gang",
                "invaded",
                "island",
                "demons",
                "spirit",
                //"Big Kahuna",
                "private banker",
                "banker",
                "surveillance",
                "Geneva",
                "bankers",
                "dictatorship",
                "Argentina",
                "tournament",
                "student",
                "academy",
                "merliah",
                "mermaid",
                "Australia",
                "whirlpool",
                //"Merliah",
                "the fun",
                "Oceana",
                "surf",
                "exciting",
                "gaming",
                "roller",
                "emoji",
                "gymnastics",
                "gymnasts",
                "spy",
                "disguises",
                "Milwaukee",
                "Professional Baseketball League",
                "invent",
                "cities",
                "losers",
                "hustler",
                "Indian",
                "London",
                "excuses",
                "strike",
                "background",
                "ballet",
                "miners",
                "Chuckie",
                "canine",
                "circus",
                "runaway circus",
                "Bingo",
                "class",
                "publicized",
                "loophole",
                "scandal",
                "shake",
                "bobbleheads",
                "bobble",
                //"ready",
                "bobblehead",
                "chin",
                "boogie",
                "college boogie",
                "Queens",
                "sanctuary",
                "enforcer",
                "Irish",
                "cousin",
                "sponsors",
                "Smails",
                "dashing",
                "Paris",
                "peter",
                "quartet",
                "French Alps",
                "coaching",
                "brood",
                "Northwestern University",
                "writer",
                "convenience",
                "clerks",
                "store clerks",
                "jockeys",
                "customers",
                "classroom",
                "headlines",
                "Richmond High School",
                "goliath",
                "trauma",
                "neuropathologist",
                "CTE",
                //"omalu",
                //"Jimmy",
                "wedding",
                "worth",
                "detectives",
                "card",
                "theft",
                "drugs",
                "centering",
                "teens",
                "pledge",
                "affair",
                "murder",
                "murdered",
                "plot",
                "German",
                "German National Soccer Team",
                "wartime",
                "prisoners",
                "pows",
                "bat",
                "World Series",
                "fear",
                "underdog",
                "giants",
                "field",
                "surprising",
                "cornfield",
                "hears",
                "farmer",
                "directions",
                "ballplayers",
                "Iowa",
                "Merciless",
                "Earth",
                "planet",
                "tyranny",
                "baseball legend",
                "woman",
                "chance",

            };
        
            return listWithDupes.Distinct().ToList();
        }
    }

    public SequenceAdvices AdviceSequence
    {
        get
        {
            return new SequenceAdvices
            {
                Events = new AdviceSequence
                {
                    OpeningImage = "Briefly show a physical or symbolic element that demonstrates this story focuses on a specific sport.",
                    Setup = "Show the sports setting in action, and how it permeates the everyday lives of the characters.",
                    FunAndGames = "Celebrate the sport by showing its highs and lows. Show the sport from multiple perspectives: the players, the fans, and the business side."
                },
                Context = new AdviceSequence
                {

                }
            };
        }
    }

}