using System;
using System.Linq;
using System.Collections.Generic;
using StoryGhost.Interfaces;

namespace StoryGhost.Models.Genres;

public class War : IGenre
{
    public string Id { get { return "war"; } }
    public string Name { get { return "War"; } }
    public string Description { get { return "The War genre is concerned with warfare, typically about naval, air, or land battles, with combat scenes central to the drama. It has been strongly associated with the 20th century. The fateful nature of battle scenes means that war stories often end with them. Themes explored include combat, survival and escape, camaraderie between soldiers, sacrifice, the futility and inhumanity of battle, the effects of war on society, and the moral and human issues raised by war."; } }
    public List<string> Keywords
    {
        get
        {
            var listWithDupes = new List<string>{
                "revolutionaries", "guerilla warfare", "prisoner", "infantry", "submarine", "Pacific", "North Africa", "Vietnam", "Axis", "Allies", "military-industrial complex", "morality", "radio", "satellite", "spy plane", "bomb", "bomber", "military objective", "brave volunteers", "Soviet", "aftermath", "Civil War", "barbed wire", "mustard gas", "nuclear", "trenches", "bayonet", "protest", "puppet regime", "helicopter",

                // GPT-3 generated
                "loyalty", "following orders", "secret mission", "infiltration", "propaganda", "civilian defense", "weapons factory", "aerial dogfight", "storm the beach", "U-boat", "aircraft carrier", "enlistment", "letters home", "ambush", "befriend enemy soldier", "rationing", "desertion", "war crimes", "treaty", "postwar", "purple heart", "parades", "shellshock", "PTSD", "veteran",

                "war",
                "American",
                "mission",
                "soldiers",
                "enemy",
                "German",
                "Nazi",
                "group",
                "love",
                "U.S.",
                "Vietnam",
                "British",
                "rescue",
                "lives",
                "battle",
                "team",
                "army",
                "lines",
                "fight",
                "Army",
                "forced",
                "French",
                "officer",
                "unit",
                "country",
                "Japanese",
                "military",
                "Germany",
                "home",
                "life",
                "save",
                "pilot",
                "elite",
                "France",
                "soldier",

                // from newest KeyBERT notbook

                "World War II",
                "soldiers",
                "American",
                "Nazi",
                "German",
                "battle",
                "mission",
                "British",
                "war",
                "French",
                "U.S.",
                "Japanese",
                "pilot",
                "soldier",
                "France",
                "Vietnam War",
                "Iraq",
                "Germany",
                "Afghanistan",
                "military",
                "colonel",
                "Vietnam",
                "Jewish",
                "fighter",
                "WWII",
                "sergeant",
                "Nazis",
                "rescue",
                "crew",
                "resistance",
                "family",
                "Britain",
                "officer",
                "English",
                "camp",
                "prisoners",
                "lines",
                "farmer",
                "enemy",
                "London",
                "England",
                "America",
                "film",
                "village",
                "marine",
                "combat",
                "troops",
                "recruits",
                "Army",
                "drama",
                "forces",
                "prisoner",
                "height",
                "CIA",
                "chaos",
                "fight",
                "pilots",
                "assassinate",
                "invasion",
                "squad",
                "African",
                "Allied",
                "Russian",
                "World War I",
                "father",
                "prison",
                //"mouse",
                "bomber",
                "United States",
                "U.S. Army",
                "Japan",
                "battles",
                "platoon",
                "squadron",
                "Navy",
                "secret",
                "Russia",
                "forced",
                "lieutenant",
                "save",
                "protect",
                "son",
                "Africa",
                "Poland",
                "deadly",
                "Belfast",
                "security",
                "Netherlands",
                "allies",
                "fly",
                "Chinese",
                "army",
                "intelligence",
                "North Africa",
                "fuhrer",
                "Berlin",
                "snipers",
                "Nigeria",
                "kingdom",
                "hiding",
                "Czech",
                "noble",
                "Irish",
                "fights",
                "Luftwaffe",
                "childhood",
                "Bosnia",
                "harrowing",
                "kidnap",
                "activist",
                "warrior",
                "odds",
                "bomb",
                "heroes",
                "battlefield",
                "submarine",
                "falls",
                "brothers",
                "wife",
                "nuclear",
                "beaches",
                "mother",
                "surrender",
                //"play",
                "sniper",
                "POWs",
                "crashes",
                "girl",
                "survival",
                "Khmer Rouge",
                "fought",
                "servicemen",
                "Spain",
                "civil",
                "captain",
                "Hawaii",
                "castle",
                "union",
                "Vietnamese",
                "desert",
                "Iraqi",
                "convoy",
                "medic",
                "jungles",
                "directors",
                "hill",
                "photographer",
                "Paris",
                "monastery",
                "reich",
                "Gulf War",
                "enlists",
                "Taliban",
                "elite",
                "militants",
                "officers",
                "World War I.",
                "land",
                "misfit",
                "cavalry",
                "regime",
                "escape",
                "Ottoman Empire",
                "Arab",
                "tribes",
                "movie",
                "legion",
                "bond",
                "dog",
                "bombing",
                "naval",
                "throne",
                "commander",
                "trial",
                "moral",
                "return",
                "terrorist",
                "devices",
                "occupation",
                "slaves",
                "trenches",
                "Gladiator",
                "fate",
                "friends",
                "map",
                "spy",
                "woman",
                "Rome",
                "dictator",
                "prince",
                "hero",
                "track",
                "reporter",
                "Turkey",
                "Australian",
                "journalist",
                "dramatic",
                "King of Sparta",
                "band",
                "Thermopylae",
                "usher",
                "Persians",
                "democracy",
                "message",
                "cross",
                "First World War",
                "safety",
                "streets",
                "riot",
                "abandons",
                "accidentally",
                "agents",
                "dismantle",
                "attacks",
                "September 11th",
                "head",
                "special",
                "Libya",
                "ambassador",
                "killed",
                "struggles",
                "compound",
                "Operation Market Garden",
                "strategically",
                "bridges",
                "breaking",
                "Austrian",
                "execution",
                "threat",
                "refusing",
                "combatants",
                "completely",
                "Balkans",
                "cows",
                "aid",
                "pacified",
                "voiceless",
                "voice",
                "correspondents",
                "globe",
                "hotspots",
                "kidnapped",
                "U.S. SEAL",
                "province",
                "giant",
                //"Alexander",
                "Persian Empire",
            };
        
            return listWithDupes.Distinct().ToList();
        }
    }

    public SequenceAdvices AdviceSequence
    {
        get
        {
            return new SequenceAdvices
            {
                Events = new AdviceSequence
                {
                    OpeningImage = "Set a militaristic tone.",
                    Setup = "Elaborate on the war-like conflict and how it impacts the protagonist."
                },
                Context = new AdviceSequence
                {

                }
            };
        }
    }

}