using System;
using System.Linq;
using System.Collections.Generic;
using StoryGhost.Interfaces;

namespace StoryGhost.Models.Genres;

public class Western : IGenre
{
    public string Id { get { return "western"; } }
    public string Name { get { return "Western"; } }
    public string Description { get { return "Western is a genre of fiction set primarily in the latter half of the 19th century and the early 20th century in the Western United States, known as the \"Old West\" or the \"Wild West\". The Western genre sometimes portrays the conquest of the wilderness and the subordination of nature in the name of civilization or the confiscation of the territorial rights of the original, Native American, inhabitants of the frontier. The Western depicts a society organized around codes of honor and personal, direct or private justice-\"frontier justice\"-dispensed by gunfights."; } }
    public List<string> Keywords
    {
        get
        {
            var listWithDupes = new List<string>{
                "cowboy", "gunslinger", "outlaw", "Wild West", "desert", "mountains", "plains", "retribution", "gunfighter", "high noon", "revolver", "pioneers", "saloon", "gambling", "bar fight", "bounty hunter", "lawmen", "gun duel", "wilderness", "code of honor", "frontier justice", "feud", "wanderer", "horse", "desolate landscape", "frontier towns", "whiskey", "tequila", "brawling", "general store", "railroad", "telegraph", "bandanna", "trusty steed", "Union Pacific", "marshal", "remorse",

                // GPT-3 generated
                "horseback", "campfire", "cattle rustlers", "gold rush", "steam engine", "farmstead", "train robbery", "sheriff", "deputy", "town jail", "stagecoach", "shootout", "showdown", "posse", "Oregon trail", "cow wrangler", "lasso", "rodeo", "cattle branding", "homesteading", "wagon train", "Native American reservation", "frontier", "cavalry", "Sioux", "Apache",

                "town",
                "gang",
                "West",
                //"help",
                "Civil War",
                "rancher",
                "life",
                "Mexico",
                "Mexican",
                "notorious",
                //"forced",
                //"group",
                "American",
                "Texas",
                //"mysterious",
                "gold",
                "local",
                //"save",
                "land",
                "brothers",
                "farm",
                "job",
                "Army",
                "home",
                "ranch",
                "fight",

                // from newest KeyBERT notbook

                "town",
                "outlaw",
                "gang",
                "Civil War",
                "rancher",
                "Mexican",
                "sheriff",
                "American",
                "cattle",
                "Texas",
                "America",
                "vengeance",
                "marshal",
                "father",
                "Apache",
                "Confederate",
                "kidnapped",
                "gunslinger",
                "adventure",
                "lawman",
                "Army",
                "frontier",
                "village",
                "Old West",
                "farmer",
                "Wild West",
                "colonel",
                "horse",
                "Mexico",
                "soldiers",
                "journey",
                "bounty",
                "gunfighter",
                "ranch",
                "family",
                "townspeople",
                "woman",
                "bandit",
                "gunman",
                "Arizona",
                "prison",
                "west",
                "threat",
                "Ireland",
                "returns",
                "railroad",
                "crime",
                "preacher",
                "desert",
                "U.S.",
                "outlaws",
                "rodeo",
                "veteran",
                "hunter",
                "land",
                "hometown",
                "gun",
                "heroes",
                "Apaches",
                "reservation",
                "justice",
                "cowboy",
                "western",
                "farm",
                "resort",
                "New Mexico",
                "American West",
                "union",
                "Indians",
                "rescue",
                "wealthy",
                "daughter",
                "West",
                "assassin",
                "mining",
                "prospector",
                "regiment",
                "frontiersman",
                "stagecoach",
                "traveling",
                "women",
                "United States",
                "rustlers",
                "gold",
                "train",
                "drought",
                "Southern Railroad",
                "murderers",
                "fall",
                "slinger",
                "cowardly",
                "incarceration",
                "cats",
                "Mousekewitz",
                "mice",
                "police",
                "Bacurau",
                "Brazilian",
                "maps",
                "mourns",
                "matriarch",
                "sertao",
                "inhabitants",
                "heiress",
                "robber",
                "heists",
                "country",
                "ravaged",
                "Great Famine",
                "reunite",
                "Feeney",
                "unbearable",
                "foreman",
                "prisoner",
                "shootout",
                "saloon",
                "genuine",
                "North-American West",
                "inferno",
                "survivor",
                "Wyoming",
                "Butch",
                "Sundance",
                "wall",
                "unstoppably",
                "Flagstone",
                "intention",
                "builders",
                "forms",
                "stoic",
                "Sioux",
                "gunslinging",
                "Red Deserts",
                "trail",
                "envisioned",
                "businessmen",
                "decide",
                "vacation envisioned",
                "relaxing",
                "vacation",
                "New York",
                "cowboys",
                "kinship",
                "Philadelphia",
                "knit",
                "desert town",
                "breeder",
                "washed",
                "boss",
                "devil",
                "servant",
                "redemption",
                "supernatural",
                "hole",
                "robbing",
                "plantation",
                "mercy",
                "rivalries",
                "alliances",
                "reunion",
                "navigate",
                "statehood",
                "camp",
                "Deadwood",
                "South Dakotas",
                "wife",
                "revolutionaries",
                "dragging",
                "coffin",
                "brutal",
                "Mississippi",
                "German",
                "slave",
                "fighter",
                "rival",
                "twin",
                "Seven Men",
                "unbeknownst",
                "film",
                "owning land",
                "boxer",
                "dream",
                "owning",
                "landlord",
                "Oklahoma",
                "loner",
                "Oregon Territory",
                "cow",
                "taciturn",
                "cook",
                "Chinese",
                "terrorizing",
                "sombre",
                "Fort Apache",
                "mythology",
                "subordinates",
                "advice",
                "hangman",
                "Madrid",
                "accused",
                "coyotes",
                "tear",
                "curse",
                "undead",
                "nun",
                "save",
                "covenant",
                "cursed",
                "farmers",
                "edge",
                "Apache Indians",
                "government",
                "corn",
                "gunfight",
                "holliday",
                "corral",
                "alliance",
                "vowing",
                "journeyman",
                "slavery",
                "Arkansas",
                "divorced",
                "West Texas",
                "Arabia",
                "massive",
                "Hidalgo",
                "Pony Express",
                "compete",
                "courier",
                "noon",
                "stranger",
                "Lago",
                "townsfolk",
                "gunfighting",
                "hire",
                "despatch",
                "rider",
                "warring",
                "protector",
                "Cheyenne",
                "escort",
                "Native American",
                "hating",
                "chief",
                "captain",
                "pioneer",
                "eyes",
                "epic",
                "development",
                "search",
            };

            return listWithDupes.Distinct().ToList();
        }
    }

    public SequenceAdvices AdviceSequence
    {
        get
        {
            return new SequenceAdvices
            {
                Events = new AdviceSequence
                {
                    OpeningImage = "Show it's the wild west."
                },
                Context = new AdviceSequence
                {

                }
            };
        }
    }

}